### ISSUE TITLE
NoSuchElementException when launching booster with Openshift online

### ISSUE THREAD

**Issue by travisrogers05** [fabric8-launcher/launcher-frontend#228] opened 2018-02-01 00:01 UTC
<img width="1030" alt="launch-openshift-online-error" src="https://user-images.githubusercontent.com/2945245/35653981-4d7996e8-06b0-11e8-866b-93db26977be4.png">

All permissions were granted to Github and Openshift Online.

Encountered while creating a booster on Openshift Online.  Looks like configuring the build triggers failed.  

Now I encounter errors because the Github repository already exists, so I am unable to continue launching the booster.

I'll remove the project from my Github repo and try again from scratch.

**Comment by travisrogers05** [comment] 2018-02-01 00:05
Deleting the git repository and then hitting the retry worked.

**Comment by gastaldi** [comment] 2018-02-01 00:12
Duplicate of https://github.com/fabric8-launcher/launcher-planning/issues/99. We made some changes in staging to display the original error (mostly caused by the OpenShift API not finding the created OpenShift project). It will soon be in production.

**Closed** 2018-02-28 08:24 UTC
