### ISSUE TITLE
Unable to create multiple applications for the same booster (without one overwriting the other)

### ISSUE THREAD

**Issue by petenorth** [fabric8-launcher/launcher-frontend#361] opened 2018-05-18 14:28 UTC
This probably affects both frontend and backend.

Use Case: As a developer I have access to a shared project containing many application deployments. I would like to be able to use the Fabric8 Launcher to create multiple applications based on the same booster .

Current behaviour: The UI allows the user to choose an existing Openshift project as long as the git repo is unique. Unfortunately the deployment configuration, build configuration, service and route all use a name based on the booster name. There should be a way of specifying the application name and have that name be used for the dc, bc, service and route.

On previous projects I have defaulted the dc,bc, service and route to the maven artifact id (the UI has the option to specify the group id and artifact id). A complete solution would allow the user to override this with a specific application name if desired.

**Comment by ia3andy** [comment] 2018-05-18 14:30
@gastaldi I think someone had the same problem few weeks ago by email?

**Comment by gastaldi** [comment] 2018-05-18 14:32
This is a duplicate of https://github.com/fabric8-launcher/launcher-planning/issues/160

**Comment by gastaldi** [comment] 2018-05-18 14:34
@petenorth Thank you for your feedback, can I ask you to create issues in the https://github.com/fabric8-launcher/launcher-planning/issues instead? We use the launcher-frontend and launcher-backend for issues specific to these components :wink: 

Btw, since this issue is a duplicate of the issue above, I'm closing it now.

Thanks!

**Closed by gastaldi** 2018-05-18 14:34 UTC
